CREATE DATABASE IF NOT EXISTS Instagram;
SHOW DATABASES;
USE Instagram;
SELECT DATABASE();

-- Users Table
CREATE TABLE IF NOT EXISTS Users
	(
		User_Id SMALLINT UNSIGNED AUTO_INCREMENT,
        User_Name VARCHAR(50) NOT NULL UNIQUE,
        Created_At TIMESTAMP DEFAULT NOW(),
        PRIMARY KEY(User_Id)
    );
SHOW COLUMNS
FROM Users;

-- Photos Table
CREATE TABLE IF NOT EXISTS Photos
	(
		Photo_Id SMALLINT UNSIGNED AUTO_INCREMENT,
        User_Id SMALLINT UNSIGNED NOT NULL,
        Image_URL VARCHAR(50) NOT NULL,
        Created_At TIMESTAMP DEFAULT NOW(),
        PRIMARY KEY(Photo_Id),
        FOREIGN KEY(User_Id) REFERENCES Users(User_Id) ON DELETE CASCADE
    );
DESC Photos;

-- Comments Table
CREATE TABLE IF NOT EXISTS Comments
	(
		Comment_Id SMALLINT UNSIGNED AUTO_INCREMENT,
        Comment_Text VARCHAR(255) NOT NULL,
        User_Id SMALLINT UNSIGNED NOT NULL,
        Photo_Id SMALLINT UNSIGNED NOT NULL,
        Created_At TIMESTAMP DEFAULT NOW(),
        PRIMARY KEY(Comment_Id),
        FOREIGN KEY(User_Id) REFERENCES Users(User_Id) ON DELETE CASCADE,
        FOREIGN KEY(Photo_Id) REFERENCES Photos(Photo_Id) ON DELETE CASCADE
    );
DESCRIBE Comments;

-- Likes Table
CREATE TABLE IF NOT EXISTS Likes
	(
		User_Id SMALLINT UNSIGNED NOT NULL,
        Photo_Id SMALLINT UNSIGNED NOT NULL,
        Created_At TIMESTAMP DEFAULT NOW(),
        FOREIGN KEY(User_Id) REFERENCES Users(User_Id) ON DELETE CASCADE,
        FOREIGN KEY(Photo_Id) REFERENCES Photos(Photo_Id) ON DELETE CASCADE,
        CONSTRAINT Not_More_Than_One_Like UNIQUE(User_Id, Photo_Id)
    );
SHOW COLUMNS
FROM Likes;

-- Follows Table
CREATE TABLE IF NOT EXISTS Follows
	(
		Follower_Id SMALLINT UNSIGNED NOT NULL,
        Followee_Id SMALLINT UNSIGNED NOT NULL,
        Created_At TIMESTAMP DEFAULT NOW(),
        FOREIGN KEY(Follower_Id) REFERENCES Users(User_Id) ON DELETE CASCADE,
        FOREIGN KEY(Followee_Id) REFERENCES Users(User_Id) ON DELETE CASCADE,
        CONSTRAINT Can_Only_Follow_Once UNIQUE(Follower_Id, Followee_Id)
    );
DESC Follows;



SHOW TABLES;