USE pet_shop;

-- NOT NULL constraint
CREATE TABLE IF NOT EXISTS cats2
	(
		Name VARCHAR(20) NOT NULL,
        Age TINYINT NOT NULL
    );

SHOW COLUMNS
FROM cats2;

-- DEFAULT Constraint
CREATE TABLE IF NOT EXISTS cats3
	(
		Name VARCHAR(20) DEFAULT 'Mystery',
        Age TINYINT UNSIGNED DEFAULT 99
    );

DESCRIBE cats3;
INSERT INTO cats3(Age)
VALUE(2);
INSERT INTO cats3() VALUE();
SELECT *
FROM cats3;

-- PRIMARY KEY and AUTO_INCREMENT
CREATE TABLE IF NOT EXISTS Unique_cats
	(
		Cat_Id TINYINT UNSIGNED AUTO_INCREMENT,
        Name VARCHAR(20) NOT NULL DEFAULT 'UnNamed',
        Age TINYINT UNSIGNED NOT NULL DEFAULT 0,
        PRIMARY KEY(Cat_Id)
    );
DESC Unique_cats;

SHOW TABLES;